### ISSUE TITLE
[BUG] Case view error 400 when trying to view case list

### ISSUE THREAD

**Issue by jtavan** [reflexsoar/reflex-api#177]
**Describe the bug**
In current code builds (API docker image pulled today 2022-05-17 with id a3e637a4ec5e), clicking on Cases in the menu brings up the view for cases, but it never populates. Inspection of the browser traffic indicates that the call to /api/v2.0/case?page=1&page_size=25&sort_by=created_at&sort_direction=asc&escalated=false returns an error 400, as does the call to /api/v2.0/case_template - no errors are logged in the reflex-api docker logs.

**To Reproduce**
1. Log in
2. Click Cases
3. The view shifts, but the pulsing circle loading indicator stays up, and the API requests result in 400 errors.

**Expected behavior**
Clicking Cases should load the cases and display them.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by n3tsurge** [comment]
Will check this out this evening, did experience something similar today

Brian Carroll
________________________________
From: Jeremy Tavan ***@***.***>
Sent: Tuesday, May 17, 2022 5:16:07 PM
To: reflexsoar/reflex-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [reflexsoar/reflex-api] [BUG] Case view error 400 when trying to view case list (Issue #177)


Describe the bug
In current code builds (API docker image pulled today 2022-05-17 with id a3e637a4ec5e), clicking on Cases in the menu brings up the view for cases, but it never populates. Inspection of the browser traffic indicates that the call to /api/v2.0/case?page=1&page_size=25&sort_by=created_at&sort_direction=asc&escalated=false returns an error 400, as does the call to /api/v2.0/case_template - no errors are logged in the reflex-api docker logs.

To Reproduce
Steps to reproduce the behavior:

  1.  Log in
  2.  Click Cases
  3.  The view shifts, but the pulsing circle loading indicator stays up, and the API requests result in 400 errors.

Expected behavior
Clicking Cases should load the cases and display them.

Desktop (please complete the following information):

  *   OS: Windows 11
  *   Browser: Chrome

**Comment by n3tsurge** [comment]
We are currently testing a fix for this issue

**Comment by n3tsurge** [comment]
This item is resolved in release v2022.05.01 (7ee694ef522c30f56c646092ed3e64a47f818240)
