### ISSUE TITLE
[BUG] Can't recreate a user with an email address that was previously removed

### ISSUE THREAD

**Issue by anrsec** [reflexsoar/reflex-api#194]
**Describe the bug**
It seems that you cannot reuse an email address for a new user account if it was part of a user account that was deleted.

**To Reproduce**
1. Create a user account A with email address admin@example.com.
2. Remove the user account A.
3. Try to create a new user account B using the same email address admin@example.com.
4. See error `User with this e-mail already exists.`

**Expected behavior**
You should be able to reuse an email address once you remove the user account associated with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/61625853/174019241-5331cf74-bfe7-414a-817c-af08ceeb142b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Chromium
 - Version: 2022.05.01

**Comment by n3tsurge** [comment]
Can you highlight when you would delete a user instead of just editing their attributes if you're just going to replace them anyway example you named them wrong username what are you just change the username and not delete the user and recreate it?

Brian Carroll
________________________________
From: Andrei R ***@***.***>
Sent: Thursday, June 16, 2022 3:47:34 AM
To: reflexsoar/reflex-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [reflexsoar/reflex-api] [BUG] Can't recreate a user with the same email address after it's removed (Issue #194)


Describe the bug
It seems that you cannot reuse an email address for a new user account if it was part of a user account that was deleted.

To Reproduce
Steps to reproduce the behavior:

  1.  Create a user account A with email address ***@***.******@***.***>.
  2.  Remove the user account A.
  3.  Try to create a new user account B using the same email address ***@***.******@***.***>.
  4.  See error User with this e-mail already exists.

Expected behavior
You should be able to reuse an email address once you remove the user account associated with it.

Screenshots
[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F61625853%2F174019241-5331cf74-bfe7-414a-817c-af08ceeb142b.png&data=05%7C01%7Cbcarroll%40zeroonesecurity.com%7C4b1014a5c29143f1ebb008da4f6c79df%7Ca68b09e0c76f40ccb262ae8575779491%7C0%7C0%7C637909624581193619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=46M6EUVQ79CZZMsP6H5FRiyAO%2FjsZWhbkVd0SWVLGfc%3D&reserved=0>

Desktop (please complete the following information):

  *   OS: Ubuntu 22.04 LTS
  *   Browser: Chromium
  *   Version: 2022.05.01

**Comment by anrsec** [comment]
For example, in my case, I accidentally deleted it. Otherwise, you're right, there would be no reason to do it while you can edit it.

**Comment by n3tsurge** [comment]
Okay yeah we soft elite users because they are referenced somewhere in the system I agree the email should be changed so that it can't be used and then another user can be created what was intended to happen was allow you to restore the deleted users and I didn't add it yet so I will bake that into the next release. For now you can go into elastic and actually update the user directly to not deleted by changing the deleted field I believe it's been a while since I looked at it

Brian Carroll
________________________________

**Comment by anrsec** [comment]
Sounds good. Thanks for the information! :grinning:

**Comment by anrsec** [comment]
Meanwhile, if anyone is looking for a fix, as Brian suggested:

```
POST /<reflex_users_index>/_update/<id>
{
    "doc" : {
        "deleted": "false",
        "locked": "false",
        "username": "user_name"
    }
}
```
