### ISSUE TITLE
Persistent Pairing Token

### ISSUE THREAD

**Issue by SMAPPER** [reflexsoar/reflex-api#43]
Add the ability to generate a persistent pairing token within the admin settings page. This would allow for use with temporal agents (docker/Kubernetes containers)

- [x] Add persistent pairing token

**Comment by n3tsurge** [comment]
@SMAPPER I think supporting a pairing token that is persistent goes against the JWT RFC.  Since admins can change the pairing token timeout period a work around would be to:

1. Change the pairing token timeout to a lengthy period
2. Grab a new pairing token
3. Change it back

This way they are accepting the risk of how they use their pairing tokens and we aren't forcing it on them.  Thoughts?

**Comment by SMAPPER** [comment]
My only concern with that is that organizations may deploy with containers and have a key that is valid for X days (assume 1 year), forget, and then out of nowhere their SOAR platform quits working.

- Can the length be 1 year or more (user-configurable)?
- Can we set up notification or warnings to the system email that a token is close to expiration?

**Comment by n3tsurge** [comment]
Users could technically go to Settings > Global Settings > Pairing Token Validity and set it to 3650 days, the token would persist for 10 years.

**Comment by SMAPPER** [comment]
Ok. That makes sense and is something I'll document. Do you think it makes sense to add an issue ticket to notify of a long running pairing token expiration coming up?

**Comment by n3tsurge** [comment]
Updated code in commit  249abf0 so that users with the `create_persistent_pairing_token` permission will be allowed to call the `/settings/generate_persistent_pairing_token` API endpoint and create a new persistent pairing token.  The token is replaced every time this API endpoint is called and the previous token is invalidated.

I will add a button the Global Settings page to make this call to the API and display it back to the user.  It will only be displayed one time.
